### PR TITLE
@probe.gl/stats: New module for Stats object

### PR DESCRIPTION
**Pull request by ibgreen**
To minimize the code size impact of using `Stats`.

### CODE REVIEW

**Comment by tsherif** [comment]
Great idea. Would it would make sense to also include stats-widget this module?

**Comment by ibgreen** [comment]
> Great idea. Would it would make sense to also include stats-widget this module?

Not in the way I currently think about this, which is that frameworks include stats, and apps optionally use the stats-widget.

Since these are micro-utils, they should have the smallest possible cost and footprint, and including the stats-widget in the stats module would then incur the cost of the widget for many apps that don't use it.

**Comment by tsherif** [comment]
Makes sense. It might be worth thinking about the conceptual lines along which you want to split things, e.g. in this case, maybe "tooling" vs "display"? It will make it easier to organize things in the future and also make the library easier to navigate.

**Comment by xintongxia** [comment]
I bumped the probe.gl packages to `v3.1.0-beta.5`

**Comment by Pessimistress** [comment]
@xintongxia 3.1.0 is already published, please use 3.2.0-alpha

**Pull request merged**
