### PR TITLE
bench: Add `options.throughput` to run async tests in parallel

### PR DESCRIPTION
**Pull request by ibgreen**
Working on some cases where it is desirable to measure the "throughput" after parallelizing async tasks, e.g.

```
    Bench.addAsync('parallel parsing of 100 buffers', {throughput: 100}, async () => {
      return parseUsingWorker(data);
    });
```

### CODE REVIEW

**Comment by Pessimistress** [comment]
`concurrency`?

**Comment by ibgreen** [comment]
> concurrency usually refers to the number of threads. throughput refers to the rate of data being processed, in my understanding.

Exactly, the intention is that this benchmark would measure the rate of data being processed, e.g. throughput of running e.g. 100 parse using smaller number of concurrent workers.

I am working on the bitmap worker loader in loaders.gl and would like to see `100 bitmap/s` kind of results.

**Comment by ibgreen** [comment]
Would also be good for measuring Draco encoder/decoder output using multiple workers. Megapoints/second...

**Comment by ibgreen** [comment]
@Pessimistress 
- Renamed `options.repetitions` to `multiplier` per discussion in previous PR.
- Renamed `options.throughput` to `_throughput` until we have time to revisit the naming.

**Pull request merged**
