### PR TITLE
fix(test-utils): Disable puppeteer timeout

### PR DESCRIPTION
**Pull request by ibgreen**
For https://github.com/visgl/loaders.gl/pull/1940

### CODE REVIEW

**Comment by ibgreen** [comment]
@ilijapuaca

**Comment by ilijapuaca** [comment]
This only makes the situation worse, no? I ran into this article too, but removing the timeout will make this hang indefinitely vs 30 seconds that it does now as far as I understand

**Comment by ibgreen** [comment]
Good question. I used to be getting the 30 second timeout message. but the tests still completed. As of Node 16, I get the message and it generates a hard error and the tests no longer complete....

**Comment by ibgreen** [comment]
Since probe.gl is currently on an alpha track it is easy enough to test this out. I will land and publish an alpha and revert if no good.

**Comment by ilijapuaca** [comment]
> Good question. I used to be getting the 30 second timeout message. but the tests still completed. As of Node 16, I get the message and it generates a hard error and the tests no longer complete....

I think the takeaway from latest discussion on this was that we want to figure out where the timeout comes from to begin with. We're seeing two types of behavior (both not good):
- All the successful runs have an error thrown after 30 seconds and continue running
- Error saying `Connection refused at localhost:5000` gets thrown and CI gets stuck until it gets killed by Github

**Comment by Pessimistress** [comment]
Link to my comment on the other thread: https://github.com/visgl/loaders.gl/pull/1940#issuecomment-969375070

**Comment by ibgreen** [comment]
Update: This PR fixed the Node 16 upgrade in loaders.gl.

**Pull request merged**
